### ISSUE TITLE
Is Builder intended to be included in the library?

### ISSUE THREAD

**Issue by kaishin** [sergdort/CombineFeedback#20]
Following the examples in my own project, I realized that the `Builder` helper protocol is not part of the library. Is that an oversight or should I just copy the `set` method directly in my own project?

**Comment by sergdort** [comment]
Hey @kaishin I've now changed `Reducer` signature from `(State, Event) -> State` to be `(inout State, Event) -> Void` so there is no need for `Builder` helper anymore, just make properties of your `State` struct `var` is they intent to be mutable

**Comment by kaishin** [comment]
Thanks! 

Feel free to close or leave the issue open as you see fit.
