### ISSUE TITLE
Duplicate declarations of feedback static methods in examples

### ISSUE THREAD

**Issue by kaishin** [sergdort/CombineFeedback#21]
I noticed that the the `when_() -> Feedback<State, Event>` static methods are defined both in the viewModel and in the corresponding enum in the examples. It's not necessary given that the view model can just access them from the enum type, ex:

```swift
...
feedback: [MoviesList.whenLoading()],
...
```

Can you please confirm that the current duplication is not the intended way?

**Comment by sergdort** [comment]
Hey @kaishin It's just to illustrate that it's possible to have a global state machine, like in `Redux` or just one per screen

**Comment by kaishin** [comment]
👍
